import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='bg-gray-100 p-4'>
          <nav>
            <ul>
              <li>
                <Link href='/about'>About</Link>
              </li>
            </ul>
          </nav>
        </header>

        <main>{children}</main>

        <footer></footer>
      </body>
    </html>
  )
}
